# Cults3D API
CULTS_USERNAME="erikslevin"
CULTS_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXX"
		
# InfluxDB 1.x
INFLUX_URL="http://influx-database.home.intern"
INFLUX_PORT="8086"
INFLUX_DB="cults3d"
INFLUX_USER="cults3d"
INFLUX_PASS="XXXXXXXXXXXXXXXXXXXXXXXXXX"
